### ISSUE TITLE
Access structs defined in package from the outside.

### ISSUE THREAD

**Issue by yura-eog** [apple/swift-asn1#60]
I am trying to derive a private key using this package. [RFC 5208](https://datatracker.ietf.org/doc/html/rfc5208#page-3) - PrivateKeyInfo

I am following the tests and have the following code:

```swift
let buffer = Array(base)
                
let result = try DER.parse(buffer)
let pkey = try PKCS8PrivateKey(derEncoded: result)
```

however, `PKCS8PrivateKey` is internal and I cannot use it.

https://github.com/apple/swift-asn1/blob/544ffa8eaec503c040ad979b2dbb7a67c39cac61/Tests/SwiftASN1Tests/ASN1Tests.swift#L201

What do you recommend?

Thanks

**Comment by yura-eog** [comment]
I see people are forking this to change scope to `public`

https://github.com/ekscrypto/swift-asn1/commit/d5beb46e86ca7bf165d0a66969cfa2d5afc3b896

**Comment by dnadoba** [comment]
The linked commit points to `PEMDocument` and that is already public.
swift-certificates can parse private keys: https://swiftpackageindex.com/apple/swift-certificates/1.5.0/documentation/x509/certificate/privatekey

**Comment by yura-eog** [comment]
> The linked commit points to `PEMDocument` and that is already public. swift-certificates can parse private keys: https://swiftpackageindex.com/apple/swift-certificates/1.5.0/documentation/x509/certificate/privatekey

Thank you 👍
